src/adapters/manifest.json
src/adapters/netsuite/index.js

This PR contains features:
1. Two type contact, Customer and Contact.
2. Contains Fax and VoiceMail case.
3. Also contains user details from realtime instead of static.

[feat]: Two Type  Contact, Fax and  voicemail Case

---

src/adapters/netsuite/index.js

1. Link Contact and Company with PhoneCall Log
2. If Contact type if Customer ignore linking.

Link contact  and Company to phone

---

.github/workflows/release.yml
src/adapters/netsuite/index.js

Link Contact withPhone Call while MessageLog

Contact and company linking with messageLog

---

src/adapters/netsuite/index.js

1. Add Call Recording Link In Note
2. Defaulf lastName in customer is firstname

Add Call Recording Link In Note

---

src/adapters/netsuite/index.js

Change displyed message for contact creation

---

src/adapters/netsuite/index.js
src/core/auth.js
src/core/contact.js
src/core/log.js

1. Token URL containing a constant account ID now made it dynamic.
2. Add subsidiary ID in contact and customer creation.

Add Subsidiary Id and made token url generic

---

src/adapters/netsuite/index.js

Response error logs was 
Now logs would be

Add detailed error logs

---

src/adapters/netsuite/index.js

Refactor error message

---

docs/crm/netsuite.md

Update netsuite doc form non-oneworld licese account users

---

src/adapters/netsuite/index.js

Use Restlet to fetch CurrentLoggedIn User

---

src/adapters/netsuite/index.js

Add permission check

---

src/adapters/netsuite/index.js

Fix StartTime and EndTime based on UserTimeZone

---

src/adapters/netsuite/index.js

Fix: Phone Call EndTime - NetSuite

---

src/adapters/manifest.json
src/adapters/netsuite/index.js

This PR is dependent on:  https://git.ringcentral.com/sushil.mall/netsuitecrmextensionsdf/-/merge_requests/9

NetSuite - Log sales order

---

docs/crm/netsuite.md

This permission is required as NetSuite has upgraded version 2024.2 to 2025.1 and encountering an issue.

Permission update for NetSuite

---

src/adapters/manifest.json
src/adapters/netsuite/index.js

Given NetSuite Options to enable/disable search contact with phone , in later version will give multi select options.

Optimise NetSuite query with setting

---

src/adapters/netsuite/index.js

This will create user notes under sales order NetSuite. In case of update callLog it will also create user notes even though notes already exist.

Call disposition for NetSuite

---

src/adapters/netsuite/index.js

Call Disposition for NetSuite Enhancement

---

src/adapters/netsuite/index.js

NetSuite does not allow more than 4000 character in the message body, So while logging the calls if customer has transcript enbaled then the message body data increased more than 4000 so Truncating transcript and adding a message at the very end.
https://community.ringcentral.com/app-connect-22/calls-won-t-log-in-netsuite-transcript-making-the-log-too-big-10390

Truncate Transcript in NetSuite

---

src/adapters/googleSheets/extra.js
src/adapters/googleSheets/index.js
src/index.js

Google sheet message logs functionality

---

src/adapters/netsuite/index.js

- Add functionality to log salesorder/opportunity with contact, earlier it was supported with customer only.

Log Salesorder and Opportunity with contact

---

docs/developers/interfaces/checkAndRefreshAccessToken.md
mkdocs.yml

chore: add docs about checkAndRefreshAccessToken

---

nodemon.json
packages/core/lib/callLogComposer.js
src/adapters/clio/index.js
src/adapters/insightly/index.js

1. Add nodemon for packages directory.
2. Fix: An issue was resolved where notes provided during callLog updates were not reflected in the CRM if no note was provided during callLog creation.
3. Fix: Clio and Insightly now properly handle multiple new lines in NoteRegex.

Fix: Update callLog with note if no note provide while createCallLog

---

packages/core/handlers/log.js
packages/core/lib/callLogComposer.js
packages/core/lib/constants.js
src/adapters/manifest.json
src/adapters/redtail/index.js
tests/callLogComposer.unit.test.js

1. Markdown support
2. Remove unnecessary code: createComposer function

Markdown support for compose log details
